-- ============================================================================
-- Quran Saya CMS — Skema Supabase
-- ============================================================================
-- IDEMPOTEN & AMAN untuk DB produksi yang SUDAH ada:
--   * hanya membuat objek yang belum ada + menambah kolom yang hilang
--   * TIDAK mengubah RLS `users`/`adzan_notification` (agar app tetap bisa
--     menulis via anon key seperti sekarang)
-- Jalankan di Supabase → SQL Editor. Aman dijalankan berulang.
-- ============================================================================

create extension if not exists pgcrypto with schema extensions;

-- ─────────────────────────────────────────────────────────────────────────
-- users : perangkat + histori belajar (DITULIS OLEH APP via anon key)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.users (
  id uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  device_id varchar null,
  device_name varchar null,
  token_firebase varchar null,
  is_reminder boolean null default false,
  version varchar null,
  platform varchar null,
  last_opened_at timestamptz null,
  last_read_ayat integer null,
  learning_name varchar null,
  learning_avatar integer null default 0,
  learning_level integer null default 1,
  learning_xp integer null default 0,
  learning_streak integer null default 0,
  learning_longest_streak integer null default 0,
  learning_lessons_done integer null default 0,
  learning_last_active_at timestamptz null,
  constraint users_pkey primary key (id)
);

-- Tambah kolom pada DB lama (aman bila sudah ada).
alter table public.users add column if not exists device_id varchar;
alter table public.users add column if not exists device_name varchar;
alter table public.users add column if not exists token_firebase varchar;
alter table public.users add column if not exists is_reminder boolean default false;
alter table public.users add column if not exists version varchar;
alter table public.users add column if not exists platform varchar;
alter table public.users add column if not exists last_opened_at timestamptz;
alter table public.users add column if not exists last_read_ayat integer;
alter table public.users add column if not exists learning_name varchar;
alter table public.users add column if not exists learning_avatar integer default 0;
alter table public.users add column if not exists learning_level integer default 1;
alter table public.users add column if not exists learning_xp integer default 0;
alter table public.users add column if not exists learning_streak integer default 0;
alter table public.users add column if not exists learning_longest_streak integer default 0;
alter table public.users add column if not exists learning_lessons_done integer default 0;
alter table public.users add column if not exists learning_last_active_at timestamptz;

create index if not exists idx_users_is_reminder on public.users (is_reminder);
create index if not exists idx_users_device_id on public.users (device_id);
create index if not exists idx_users_last_opened on public.users (last_opened_at desc);
create index if not exists idx_users_learning_active on public.users (learning_last_active_at desc);

-- ─────────────────────────────────────────────────────────────────────────
-- adzan_notification : preferensi adzan per user (DITULIS OLEH APP)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.adzan_notification (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  user_id uuid null,
  city_name varchar null,
  is_imsak boolean null default false,
  is_subuh boolean null default false,
  is_dzuhur boolean null default false,
  is_ashar boolean null default false,
  is_maghrib boolean null default false,
  is_isya boolean null default false,
  imsak_time varchar null,
  subuh_time varchar null,
  dzuhur_time varchar null,
  ashar_time varchar null,
  maghrib_time varchar null,
  isya_time varchar null,
  constraint adzan_notification_pkey primary key (id)
);
alter table public.adzan_notification add column if not exists is_imsak boolean default false;
alter table public.adzan_notification add column if not exists imsak_time varchar;
create index if not exists idx_adzan_notification_user_id on public.adzan_notification (user_id);

-- ─────────────────────────────────────────────────────────────────────────
-- admin : akun login CMS (dikelola CMS)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.admin (
  id uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  email varchar not null,
  password_hash text not null,
  full_name varchar null,
  is_active boolean not null default true,
  last_login_at timestamptz null,
  constraint admin_pkey primary key (id),
  constraint admin_email_unique unique (email)
);

-- ─────────────────────────────────────────────────────────────────────────
-- custom_reminders : pengingat harian terjadwal (dikelola CMS)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.custom_reminders (
  id uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text not null,
  body text not null,
  schedule_time varchar not null,   -- 'HH:MM'
  is_active boolean not null default true,
  sort_order int not null default 0,
  constraint custom_reminders_pkey primary key (id)
);
create index if not exists idx_custom_reminders_active
  on public.custom_reminders (is_active, schedule_time, sort_order);

-- ─────────────────────────────────────────────────────────────────────────
-- notification_logs : audit notifikasi (dikelola CMS)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.notification_logs (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  user_id uuid null,
  source_type varchar null,         -- adzan | reminder | manual | winback
  category varchar null,
  title text null,
  body text null,
  status varchar null default 'queued', -- queued | sent | failed | partial
  error_message text null,
  scheduled_time varchar null,      -- 'HH:MM'
  metadata jsonb null,
  dedupe_key text null,
  sent_at timestamptz null,
  constraint notification_logs_pkey primary key (id)
);
create index if not exists idx_notification_logs_created_at on public.notification_logs (created_at desc);
create index if not exists idx_notification_logs_status on public.notification_logs (status, source_type);
create unique index if not exists idx_notification_logs_dedupe_key
  on public.notification_logs (dedupe_key) where dedupe_key is not null;

-- ─────────────────────────────────────────────────────────────────────────
-- RPC admin_login : verifikasi bcrypt di DB (hash tak pernah keluar)
-- ─────────────────────────────────────────────────────────────────────────
create or replace function public.admin_login(email text, password text)
returns table (id uuid, email text, full_name text)
language sql
security definer
set search_path = public
as $$
  select a.id, a.email::text, a.full_name::text
  from public.admin a
  where lower(a.email) = lower(trim(admin_login.email))
    and a.is_active = true
    and a.password_hash = extensions.crypt(admin_login.password, a.password_hash)
  limit 1;
$$;

-- ─────────────────────────────────────────────────────────────────────────
-- Seed reminder default (HANYA bila tabel kosong)
-- ─────────────────────────────────────────────────────────────────────────
insert into public.custom_reminders (title, body, schedule_time, is_active, sort_order)
select 'Reminder Subuh', 'Sudah sholat subuh? Yuk baca beberapa ayat dulu.', '05:30', true, 1
where not exists (select 1 from public.custom_reminders);

-- ============================================================================
-- CATATAN RLS
-- ============================================================================
-- Skrip ini SENGAJA tidak menyentuh RLS. Tabel `users` & `adzan_notification`
-- diakses app via anon key; mengubah RLS berisiko merusak app live.
-- Tabel admin/custom_reminders/notification_logs diakses CMS via service-role
-- (melewati RLS) di server, di balik login admin.
-- ============================================================================
