create extension if not exists pgcrypto with schema extensions;

create table if not exists public.users (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  token_firebase character varying null,
  is_reminder boolean null default false,
  device_id character varying null,
  device_name character varying null,
  version character varying null,
  platform character varying null,
  last_opened_at timestamp with time zone null,
  last_read_ayat integer null,
  -- Histori fitur Belajar Ngaji
  learning_name character varying null,
  learning_avatar integer null default 0,
  learning_level integer null default 1,
  learning_xp integer null default 0,
  learning_streak integer null default 0,
  learning_longest_streak integer null default 0,
  learning_lessons_done integer null default 0,
  learning_last_active_at timestamp with time zone null,
  constraint users_pkey primary key (id)
) tablespace pg_default;

-- DB lama yang sudah punya tabel users: tambahkan kolom yang dipakai app.
alter table public.users add column if not exists version character varying;
alter table public.users add column if not exists platform character varying;
alter table public.users add column if not exists last_opened_at timestamp with time zone;
alter table public.users add column if not exists last_read_ayat integer;
-- Kolom histori Belajar Ngaji
alter table public.users add column if not exists learning_name character varying;
alter table public.users add column if not exists learning_avatar integer default 0;
alter table public.users add column if not exists learning_level integer default 1;
alter table public.users add column if not exists learning_xp integer default 0;
alter table public.users add column if not exists learning_streak integer default 0;
alter table public.users add column if not exists learning_longest_streak integer default 0;
alter table public.users add column if not exists learning_lessons_done integer default 0;
alter table public.users add column if not exists learning_last_active_at timestamp with time zone;

create table if not exists public.adzan_notification (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null default gen_random_uuid(),
  city_name character varying null,
  is_subuh boolean null,
  is_dzuhur boolean null,
  is_ashar boolean null,
  is_maghrib boolean null,
  is_isya boolean null,
  subuh_time character varying null,
  dzuhur_time character varying null,
  ashar_time character varying null,
  maghrib_time character varying null,
  isya_time character varying null,
  constraint adzan_notification_pkey primary key (id)
) tablespace pg_default;

create table if not exists public.admin (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  email character varying not null,
  password_hash text not null,
  full_name character varying null,
  is_active boolean not null default true,
  last_login_at timestamp with time zone null,
  constraint admin_pkey primary key (id),
  constraint admin_email_key unique (email)
) tablespace pg_default;

create table if not exists public.custom_reminders (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  title text not null,
  body text not null,
  schedule_time varchar(5) not null,
  is_active boolean not null default true,
  sort_order int not null default 0,
  constraint custom_reminders_pkey primary key (id)
) tablespace pg_default;

create table if not exists public.notification_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null,
  source_type varchar(20) not null,
  category varchar(50) null,
  title text not null,
  body text not null,
  status varchar(20) not null default 'queued',
  error_message text null,
  scheduled_time varchar(5) null,
  metadata jsonb not null default '{}'::jsonb,
  dedupe_key text null,
  sent_at timestamp with time zone null,
  constraint notification_logs_pkey primary key (id)
) tablespace pg_default;

-- (cron_job_runs dihapus: hanya ditulis tiap menit & tak pernah dibaca →
--  membengkak tanpa guna. Audit nyata ada di notification_logs.)
drop table if exists public.cron_job_runs;

create or replace function public.admin_login(email text, password text)
returns table (
  id uuid,
  email text,
  full_name text
)
language sql
security definer
set search_path = public
as $$
  select a.id, a.email::text, a.full_name::text
  from public.admin a
  where lower(a.email) = lower(trim(admin_login.email))
    and a.is_active = true
    and a.password_hash = extensions.crypt(admin_login.password, a.password_hash)
  limit 1;
$$;

create index if not exists idx_users_is_reminder on public.users (is_reminder);
create index if not exists idx_users_device_id on public.users (device_id);
create index if not exists idx_adzan_notification_created_at on public.adzan_notification (created_at desc);
create index if not exists idx_adzan_notification_user_id on public.adzan_notification (user_id);
create index if not exists idx_admin_email on public.admin (email);
create index if not exists idx_custom_reminders_active on public.custom_reminders (is_active, schedule_time, sort_order);
create index if not exists idx_notification_logs_created_at on public.notification_logs (created_at desc);
create index if not exists idx_notification_logs_status on public.notification_logs (status, source_type);
create unique index if not exists idx_notification_logs_dedupe_key on public.notification_logs (dedupe_key) where dedupe_key is not null;

insert into public.custom_reminders (title, body, schedule_time, is_active, sort_order)
select 'Reminder Subuh', 'Sudah sholat subuhnya? Yuk baca 10 ayat dulu.', '05:30', true, 1
where not exists (select 1 from public.custom_reminders where schedule_time = '05:30');

insert into public.custom_reminders (title, body, schedule_time, is_active, sort_order)
select 'Reminder Dzuhur', 'Sudah sholat dzuhur? Yuk baca 10 ayat dulu.', '13:00', true, 2
where not exists (select 1 from public.custom_reminders where schedule_time = '13:00');

insert into public.custom_reminders (title, body, schedule_time, is_active, sort_order)
select 'Reminder Ashar', 'Sudah sholat ashar? Yuk baca 10 ayat dulu.', '16:00', true, 3
where not exists (select 1 from public.custom_reminders where schedule_time = '16:00');

-- ── Buat akun admin pertama (untuk login CMS) ──
-- Ganti email & password di bawah, lalu jalankan. Password di-hash bcrypt;
-- RPC admin_login membandingkannya dengan extensions.crypt().
insert into public.admin (email, password_hash, full_name, is_active)
select
  'admin@quransaya.id',
  extensions.crypt('GANTI_PASSWORD_INI', extensions.gen_salt('bf')),
  'Administrator',
  true
where not exists (select 1 from public.admin where email = 'admin@quransaya.id');
